# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "ECEn 320: Fundamentals of Digital Systems"
class_name: Fundamentals of Digital Systems
class_number: ECEn 320
email: scott_lloyd@byu.edu
description: This is the lab website for the ECEn 320 course.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: pretty

# Build settings
markdown: kramdown
#highlighter: rouge
enable_coderay: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  
# Turn on the button to allow students to submit PRs to change a page
suggest_edits:
  enable: true

# Set the color theme of the page
colors:
  text_color: "#111"
  background_color: "#fdfdfd"
  brand_color: "rgb(46, 94, 250)"
  secondary_color: "#c3e6ef"
  text_selection_color: "rgba(0, 98, 184, .5)"
  sidebar_hover_color: "#0062B8"

# Set the fonts
fonts:
  base: "'neue-haas-unica', 'Helvetica Neue', Helvetica, Arial, sans-serif"
  # header: "omnium, sans-serif"
  # If you want a more traditional font, consider using this instead:
  header: "'Ubuntu', sans-serif"

collections:
  labs:
    output: true
    permalink: /:collection/:name/
  pages:
    output: true
    permalink: /:name/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - icon.ai
  - Dockerfile
  - Makefile
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - lab_0.io
  - old/
  - labsTBD/
  - unusedPages/
  - powerpointExcelWord/
  - README.md
  - README_ECEn220.md
  - TODO_items.md
  - JOURNAL.md
  - LINKCHECK.md
  - Makefile

# I have the compiled files being put into _site since I often mistakenly open it since it is in the middle of my files list.
# Changing it to get it at the top of the list to avoid that
#destination: _0site

